# Generated by Django 2.2.5 on 2019-11-07 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfRol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': ('Rol',),
                'verbose_name_plural': ('Roles',),
                'db_table': 'conf_rol',
            },
        ),
        migrations.CreateModel(
            name='GenrGeneral',
            fields=[
                ('idgenr_general', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': ('Lista',),
                'verbose_name_plural': ('Listas',),
                'db_table': 'genr_general',
            },
        ),
        migrations.CreateModel(
            name='MantPersona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('fecha_de_nacimiento', models.DateField()),
                ('estado', models.IntegerField()),
                ('foto', models.ImageField(upload_to='')),
                ('identificacion', models.CharField(max_length=50, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateTimeField()),
                ('usuario_ing', models.CharField(max_length=60)),
                ('terminal_ing', models.CharField(max_length=60)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('celular', models.CharField(max_length=15)),
                ('lugar_nacimiento', models.CharField(max_length=45)),
                ('discapacidad', models.IntegerField()),
                ('discapacidad_renal', models.IntegerField()),
                ('discapacidad_neurologica', models.IntegerField()),
                ('enfermedad_alergica', models.IntegerField()),
                ('asma', models.IntegerField()),
                ('epilepsia', models.IntegerField()),
                ('enfermedad_congenita', models.IntegerField()),
                ('enfermedad_respiratoria', models.IntegerField()),
                ('atencion_psicologica', models.IntegerField()),
                ('bono_solidario', models.IntegerField()),
                ('mienbros_hogar', models.IntegerField()),
                ('pnombres', models.CharField(max_length=45)),
                ('papellidos', models.CharField(max_length=45)),
                ('pidentificacion', models.IntegerField(unique=True)),
                ('pdireccion', models.CharField(max_length=45)),
                ('ptelefono', models.CharField(max_length=45)),
                ('pvive_con_usted', models.IntegerField()),
                ('mnombres', models.CharField(max_length=45)),
                ('mapellidos', models.CharField(max_length=45)),
                ('mdireccion', models.CharField(max_length=45)),
                ('mtelefono', models.CharField(max_length=45)),
                ('midentificacion', models.IntegerField(unique=True)),
                ('mvive_con_usted', models.IntegerField()),
                ('rnombres', models.CharField(max_length=45)),
                ('rapellidos', models.CharField(max_length=45)),
                ('rdireccion', models.CharField(max_length=45)),
                ('rtelefono', models.CharField(max_length=45)),
                ('rvive_con_usted', models.IntegerField()),
                ('ridentificacion', models.CharField(max_length=13, unique=True)),
                ('id_genr_categoria_migratoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_migratoria', to='GestionAcademica.GenrGeneral')),
                ('id_genr_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudad', to='GestionAcademica.GenrGeneral')),
                ('id_genr_estado_civil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_civil', to='GestionAcademica.GenrGeneral')),
                ('id_genr_estado_laboralm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_laboralm', to='GestionAcademica.GenrGeneral')),
                ('id_genr_estado_laboralp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_laboralp', to='GestionAcademica.GenrGeneral')),
                ('id_genr_etnia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etnia', to='GestionAcademica.GenrGeneral')),
                ('id_genr_genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genero', to='GestionAcademica.GenrGeneral')),
                ('id_genr_idioma_ancestral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acestral', to='GestionAcademica.GenrGeneral')),
                ('id_genr_indigena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indigena', to='GestionAcademica.GenrGeneral')),
                ('id_genr_jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornada', to='GestionAcademica.GenrGeneral')),
                ('id_genr_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAcademica.GenrGeneral')),
                ('id_genr_provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincia', to='GestionAcademica.GenrGeneral')),
                ('id_genr_tipo_identificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identificacion', to='GestionAcademica.GenrGeneral')),
                ('id_genr_tipo_parentesco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_parentesco', to='GestionAcademica.GenrGeneral')),
                ('id_genr_tipo_sangre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_de_sangre', to='GestionAcademica.GenrGeneral')),
                ('id_genr_tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_tipo_usuario', to='GestionAcademica.GenrGeneral')),
            ],
            options={
                'verbose_name': ('Persona',),
                'verbose_name_plural': ('Personas',),
                'db_table': 'mant_persona',
            },
        ),
        migrations.CreateModel(
            name='MantRepresentante',
            fields=[
                ('id_representante', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_ing', models.CharField(max_length=45)),
                ('fecha_ingreso', models.DateTimeField()),
                ('terminal_ing', models.CharField(max_length=45)),
                ('ingresos_totales', models.FloatField()),
                ('id_usuario', models.IntegerField()),
                ('id_genr_nivel_formacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAcademica.GenrGeneral')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAcademica.MantPersona')),
            ],
            options={
                'verbose_name': ('Representante',),
                'verbose_name_plural': ('Representantes',),
                'db_table': 'mant_representante',
            },
        ),
        migrations.CreateModel(
            name='ConfUsuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=45)),
                ('clave', models.CharField(max_length=45)),
                ('id_genr_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado', to='GestionAcademica.GenrGeneral')),
                ('id_genr_tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_tipo_usuario', to='GestionAcademica.GenrGeneral')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAcademica.MantPersona')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAcademica.ConfRol')),
            ],
            options={
                'verbose_name': ('Usuario',),
                'verbose_name_plural': ('Usuarios',),
                'db_table': 'conf_usuario',
            },
        ),
        migrations.CreateModel(
            name='ConfModulo',
            fields=[
                ('id_modulo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20)),
                ('id_genr_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAcademica.GenrGeneral')),
            ],
            options={
                'verbose_name': ('Modulo',),
                'verbose_name_plural': ('Modulos',),
                'db_table': 'conf_modulo',
            },
        ),
        migrations.CreateModel(
            name='ConfMenu',
            fields=[
                ('id_menu', models.AutoField(primary_key=True, serialize=False)),
                ('id_padre', models.IntegerField()),
                ('orden', models.IntegerField()),
                ('version', models.CharField(max_length=45)),
                ('id_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAcademica.ConfModulo')),
            ],
            options={
                'verbose_name': ('Menu',),
                'verbose_name_plural': ('Menus',),
                'db_table': 'conf_menu',
            },
        ),
        migrations.CreateModel(
            name='ConfEmpresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('razon_social', models.CharField(max_length=200)),
                ('identificacion', models.CharField(max_length=50, unique=True)),
                ('direccion', models.CharField(max_length=50)),
                ('representante_legal', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('fecha_creacion', models.DateField()),
                ('fecha_ingreso', models.DateField()),
                ('usuario_ing', models.CharField(max_length=45)),
                ('terminal_ing', models.CharField(max_length=45)),
                ('id_genr_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_empresa', to='GestionAcademica.GenrGeneral')),
                ('id_genr_tipo_identificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAcademica.GenrGeneral')),
            ],
            options={
                'verbose_name': ('Empresa',),
                'verbose_name_plural': ('Empresas',),
                'db_table': 'conf_empresa',
            },
        ),
    ]
