# Generated by Django 2.2.5 on 2020-03-06 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAcademica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confpermiso',
            name='acciones',
        ),
    ]
