# Generated by Django 2.2.5 on 2019-11-07 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAcademica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MantEstudiante',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_estudiante', models.CharField(max_length=45)),
                ('fecha_ingreso', models.DateTimeField()),
                ('usuario_ing', models.CharField(max_length=45)),
                ('terminal_ing', models.CharField(max_length=45)),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_estudiante_persona', to='GestionAcademica.MantPersona')),
            ],
            options={
                'verbose_name': ('Estudiante',),
                'verbose_name_plural': ('Estudiantes',),
                'db_table': 'mant_estudiante',
            },
        ),
    ]
