# Generated by Django 2.2.5 on 2019-11-12 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAcademica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantpersona',
            name='direccion',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='mantpersona',
            name='mapellidos',
            field=models.CharField(default='no requerido', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='mantpersona',
            name='mdireccion',
            field=models.CharField(default='no requerido', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='mantpersona',
            name='midentificacion',
            field=models.CharField(default='no requerido', max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mantpersona',
            name='mnombres',
            field=models.CharField(default='no requerido', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='mantpersona',
            name='mtelefono',
            field=models.CharField(default='no requerido', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='mantpersona',
            name='mvive_con_usted',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mantpersona',
            name='papellidos',
            field=models.CharField(default='no requerido', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='mantpersona',
            name='pdireccion',
            field=models.CharField(default='no requerido', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='mantpersona',
            name='pidentificacion',
            field=models.CharField(default='no requerido', max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mantpersona',
            name='pnombres',
            field=models.CharField(default='no requerido', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='mantpersona',
            name='ptelefono',
            field=models.CharField(default='no requerido', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='mantpersona',
            name='pvive_con_usted',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mantpersona',
            name='rapellidos',
            field=models.CharField(default='no requerido', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='mantpersona',
            name='ridentificacion',
            field=models.CharField(default='no requerido', max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mantpersona',
            name='rtelefono',
            field=models.CharField(default='no requerido', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='mantpersona',
            name='rvive_con_usted',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
