# Generated by Django 2.2.5 on 2020-02-12 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAcademica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfCorreosSmpt',
            fields=[
                ('id_correos_smpt', models.AutoField(primary_key=True, serialize=False)),
                ('ssl', models.CharField(max_length=30)),
                ('dominio', models.CharField(max_length=30)),
                ('puerto', models.CharField(max_length=20)),
                ('usuario_c', models.CharField(max_length=100)),
                ('contraseña_c', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': ('Correos Smpt',),
                'verbose_name_plural': ('Correos Smpt',),
                'db_table': 'conf_correos_smpt',
            },
        ),
        migrations.AddField(
            model_name='confmodulo_menu',
            name='id_genr_estado',
            field=models.ForeignKey(db_column='id_genr_estado', default='97', on_delete=django.db.models.deletion.CASCADE, to='GestionAcademica.GenrGeneral'),
        ),
        migrations.CreateModel(
            name='ConfDetallePermiso',
            fields=[
                ('id_detalle_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('id_accion', models.ForeignKey(db_column='id_accion', on_delete=django.db.models.deletion.CASCADE, related_name='fk_det_permiso_accion', to='GestionAcademica.ConfAccion')),
                ('id_genr_estado', models.ForeignKey(db_column='id_genr_estado', on_delete=django.db.models.deletion.CASCADE, to='GestionAcademica.GenrGeneral')),
                ('id_menu', models.ForeignKey(db_column='id_menu', on_delete=django.db.models.deletion.CASCADE, related_name='fk_det_permiso_menu', to='GestionAcademica.ConfMenu')),
                ('id_permiso', models.ForeignKey(db_column='id_permiso', on_delete=django.db.models.deletion.CASCADE, related_name='fk_det_permiso_cab_permiso', to='GestionAcademica.ConfPermiso')),
            ],
            options={
                'verbose_name': ('Detalle Permiso',),
                'verbose_name_plural': ('Detalle Permisos',),
                'db_table': 'conf_detalle_permiso',
            },
        ),
    ]
