# Generated by Django 2.2.5 on 2020-02-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAcademica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confaccion',
            name='id_menu',
            field=models.ManyToManyField(blank=True, db_table='detalle_accion', to='GestionAcademica.ConfMenu'),
        ),
    ]
