# Generated by Django 2.2.5 on 2021-02-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAcademica', '0002_auto_20210211_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantpersona',
            name='cargo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='mantpersona',
            name='departamento',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='mantpersona',
            name='estado_jornada',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='mantpersona',
            name='fecha_ingreso_magis',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='mantpersona',
            name='fecha_ult_acc_personal',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mantpersona',
            name='num_ult_accion_personal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mantpersona',
            name='tipo_nombramiento',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='mantpersona',
            name='fecha_ingreso',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mantpersona',
            name='fecha_ingreso_jor',
            field=models.DateTimeField(null=True),
        ),
    ]
