# Generated by Django 2.2.5 on 2019-11-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAcademica', '0002_auto_20191112_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantpersona',
            name='rnombres',
            field=models.CharField(default='no requerido', max_length=45, null=True),
        ),
    ]
