# Generated by Django 2.2.5 on 2019-11-07 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAcademica', '0002_mantestudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='MantAnioLectivo',
            fields=[
                ('id_anio_lectivo', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField()),
                ('ciclo', models.IntegerField()),
                ('fecha_incio_ciclo', models.DateField()),
                ('fecha_fin_ciclo', models.DateField()),
                ('id_genr_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_aniolectivo_estado', to='GestionAcademica.GenrGeneral')),
            ],
            options={
                'verbose_name': ('Año lectivo',),
                'verbose_name_plural': ('Año lectivo',),
                'db_table': 'mant_anio_lectivo',
            },
        ),
    ]
