# Generated by Django 2.2.5 on 2020-02-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAcademica', '0002_auto_20200211_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confcorreossmpt',
            old_name='contraseña_c',
            new_name='contrasenia_c',
        ),
        migrations.AddField(
            model_name='mantpersona',
            name='rdireccion_trabajo',
            field=models.CharField(default='no requerido', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mantpersona',
            name='rhorario_laboral',
            field=models.CharField(default='no requerido', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='mantpersona',
            name='rtelefono_trabajo',
            field=models.CharField(default='no requerido', max_length=20, null=True),
        ),
    ]
