# Generated by Django 2.2.5 on 2020-02-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAcademica', '0002_auto_20200227_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confaccion',
            name='id_menu',
            field=models.ManyToManyField(blank=True, db_table='conf_detalle_accion', to='GestionAcademica.ConfMenu'),
        ),
    ]
