# Generated by Django 2.2.5 on 2020-03-03 19:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAcademica', '0003_auto_20200303_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confaccion',
            name='descripcion',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='confpermiso',
            name='acciones',
            field=models.ManyToManyField(db_table='Conf_permiso_accion', related_name='fk_permiso_accion', to='GestionAcademica.ConfAccion'),
        ),
        migrations.AlterField(
            model_name='confpermiso',
            name='menu',
            field=models.ManyToManyField(db_table='conf_permiso_menu', related_name='fk_permiso_modmenu', to='GestionAcademica.ConfMenu'),
        ),
        migrations.AlterField(
            model_name='usuariotemp',
            name='fecha_creacion',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 3, 3, 19, 20, 41, 21223, tzinfo=utc), null=True),
        ),
    ]
