# Generated by Django 2.2.5 on 2021-02-13 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAcademica', '0003_auto_20210212_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantpersona',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='mantpersona',
            name='categoria_doc',
        ),
        migrations.RemoveField(
            model_name='mantpersona',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='mantpersona',
            name='estado_jornada',
        ),
        migrations.RemoveField(
            model_name='mantpersona',
            name='tipo_nombramiento',
        ),
        migrations.AddField(
            model_name='mantpersona',
            name='id_cargo',
            field=models.ForeignKey(db_column='id_cargo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo', to='GestionAcademica.GenrGeneral'),
        ),
        migrations.AddField(
            model_name='mantpersona',
            name='id_categoria_doc',
            field=models.ForeignKey(db_column='id_categoria_doc', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoria_docente', to='GestionAcademica.GenrGeneral'),
        ),
        migrations.AddField(
            model_name='mantpersona',
            name='id_departamento',
            field=models.ForeignKey(db_column='id_departamento', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departamento', to='GestionAcademica.GenrGeneral'),
        ),
        migrations.AddField(
            model_name='mantpersona',
            name='id_estado_jornada',
            field=models.ForeignKey(db_column='id_estado_jornada', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='GestionAcademica.GenrGeneral'),
        ),
        migrations.AddField(
            model_name='mantpersona',
            name='id_tipo_nombramiento',
            field=models.ForeignKey(db_column='id_tipo_nombramiento', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nombramiento', to='GestionAcademica.GenrGeneral'),
        ),
    ]
