# Generated by Django 2.2.5 on 2019-11-07 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAcademica', '0003_mantaniolectivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovAdmision',
            fields=[
                ('id_admision', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=45)),
                ('documento', models.CharField(max_length=45)),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_admision_estudiante', to='GestionAcademica.MantEstudiante')),
            ],
            options={
                'verbose_name': 'Admision',
                'verbose_name_plural': 'Admisiones',
                'db_table': 'mov_admision',
            },
        ),
    ]
