# Generated by Django 2.2.5 on 2019-11-07 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAcademica', '0004_movadmision'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovCabCurso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=10)),
                ('cupo', models.IntegerField()),
                ('id_anio_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_cabcurso_aniolectivo', to='GestionAcademica.MantAnioLectivo')),
                ('id_genr_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_cabcurso_curso', to='GestionAcademica.GenrGeneral')),
                ('id_genr_formacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_cabcurso_formacion', to='GestionAcademica.GenrGeneral')),
                ('id_genr_jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_cabcurso_jornada', to='GestionAcademica.GenrGeneral')),
                ('id_genr_paralelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_cabcurso_paralelo', to='GestionAcademica.GenrGeneral')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'mov_cab_curso',
            },
        ),
    ]
