# Generated by Django 2.2.5 on 2019-11-07 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAcademica', '0005_movcabcurso'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovDetalleEmpleado',
            fields=[
                ('id_detalle_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('id_anio_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_detalleEmpleado_aniolectivo', to='GestionAcademica.GenrGeneral')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_detalleEmpleado_cabcurso', to='GestionAcademica.MovCabCurso')),
                ('id_genr_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_detalleEmpleado_materia', to='GestionAcademica.GenrGeneral')),
                ('id_genr_paralelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_detalleEmpleado_paralelo', to='GestionAcademica.GenrGeneral')),
            ],
            options={
                'verbose_name': 'Detalle Empleado',
                'verbose_name_plural': 'Detalle Empleados',
                'db_table': 'mov_detalle_empleado',
            },
        ),
    ]
