# Generated by Django 2.2.5 on 2019-11-07 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAcademica', '0007_movdetallemateriacurso'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovDetalleRegistroNotas',
            fields=[
                ('id_detalle_registro_notas', models.AutoField(primary_key=True, serialize=False)),
                ('primer_parcial', models.FloatField()),
                ('segundo_parcial', models.FloatField()),
                ('tercer_parcial', models.FloatField()),
                ('examen', models.FloatField()),
                ('promedio', models.FloatField()),
                ('total_promedio_general', models.FloatField()),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_detalleregistronotas_estudiante', to='GestionAcademica.MantEstudiante')),
                ('id_general_quimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_detalleregistronotas_quimestre', to='GestionAcademica.GenrGeneral')),
            ],
            options={
                'verbose_name': 'Detalle Registro de Curso',
                'verbose_name_plural': 'Detalle Registro de Curso',
                'db_table': 'mov_detalle_registro_notas',
            },
        ),
    ]
