# Generated by Django 2.2.5 on 2019-11-07 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAcademica', '0008_movdetalleregistronotas'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovEstudianteAsignacionCurso',
            fields=[
                ('id_estudiante_curso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateTimeField()),
                ('usuario_ing', models.CharField(max_length=45)),
                ('terminal_ing', models.CharField(max_length=45)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_estudianteAsignacioncurso_movcabcurso', to='GestionAcademica.MovCabCurso')),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_estudianteAsignacioncurso_estudiante', to='GestionAcademica.MantEstudiante')),
            ],
            options={
                'verbose_name': 'Asignacion de curso',
                'verbose_name_plural': 'Asignacion de curso',
                'db_table': 'mov_estudiante_asignacion_curso',
            },
        ),
    ]
