# Generated by Django 2.2.5 on 2019-11-07 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAcademica', '0010_movmatriculacionestudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='MantEmpleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateTimeField()),
                ('usuario_ing', models.CharField(max_length=45)),
                ('terminal_ing', models.CharField(max_length=45)),
                ('id_anio_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_empleado_anio_lectivo', to='GestionAcademica.MantAnioLectivo')),
                ('id_detalle_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_empleado_detalle', to='GestionAcademica.MovDetalleEmpleado')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_empleado_persona', to='GestionAcademica.MantPersona')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_empleado_usuario', to='GestionAcademica.ConfUsuario')),
            ],
            options={
                'verbose_name': ('Empleado',),
                'verbose_name_plural': ('Empleados',),
                'db_table': 'mant_empleado',
            },
        ),
    ]
