# Generated by Django 2.2.5 on 2019-11-07 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAcademica', '0011_mantempleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovCabRegistroNotas',
            fields=[
                ('id_registro_notas', models.AutoField(primary_key=True, serialize=False)),
                ('promedio_curso_1q', models.FloatField()),
                ('promedio_curso_2q', models.FloatField()),
                ('promedio_curso_general', models.FloatField()),
                ('id_anio_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_registronotas_anniolectivo', to='GestionAcademica.MantAnioLectivo')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_registronotas_cabcurso', to='GestionAcademica.MovCabCurso')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_registronotas_empleado', to='GestionAcademica.MantEmpleado')),
                ('id_genr_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_registronotas_materia', to='GestionAcademica.GenrGeneral')),
            ],
            options={
                'verbose_name': 'Registro Notas',
                'verbose_name_plural': 'Registro Notas',
                'db_table': 'mov_cab_registro_notas',
            },
        ),
    ]
