# Generated by Django 2.2.5 on 2019-11-07 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAcademica', '0012_movcabregistronotas'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenrHistorial',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('modulo', models.CharField(max_length=50)),
                ('accion', models.CharField(max_length=50)),
                ('usuario_mod', models.CharField(max_length=50)),
                ('terminal_mod', models.CharField(max_length=50)),
                ('fecha_mod', models.DateField()),
                ('id_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_genrhistorial_confmenu', to='GestionAcademica.ConfMenu')),
            ],
            options={
                'verbose_name': ('Lista',),
                'verbose_name_plural': ('Listas',),
                'db_table': 'genr_historial',
            },
        ),
    ]
